### ISSUE TITLE
Cannot build with Cordova 9.0.1

### ISSUE THREAD

**Issue by hiensiga** [PeterHdd/cordova-plugin-crypto-file#5]
Hi team,

I add this plugin in cordova project but i cannot build it (iOS).
```
cordova build ios
```
This is following error.
Cannot find module 'q'

**Comment by hiensiga** [comment]
Cannot find module 'q'

resolve with 
```
npm install q
```

Alternatively, you can fix it by remove q module and use Promise native. Following:
https://github.com/apache/cordova-lib/pull/710
